import { DButton, DConnectionError, DDataTable, DEmptyState, DLoadingIndicator, DStatusFilter, type TableAction, type TableColumn } from '@digvation-labs/ui';
import { useState } from 'react';
import { InstallationDetailDialog } from '../components/installation-detail-dialog';
import { InstallationFormDialog } from '../components/installation-form-dialog';
import { InstallationStatusBadge } from '../components/installation-status-badge';
import { useInstallationList } from '../hooks/use-installations';
import type { InstallationEnvironment, InstallationListQuery, InstallationStatus, InstallationSummary } from '../types/installation';
import '../installations.css';
const LIMIT = 10;
const STATUS_OPTIONS = [{ value: 'PROVISIONING', label: 'Provisioning' }, { value: 'ACTIVE', label: 'Active' }, { value: 'SUSPENDED', label: 'Suspended' }, { value: 'DECOMMISSIONED', label: 'Decommissioned' }];
const ENVIRONMENT_OPTIONS = [{ value: 'PRODUCTION', label: 'Production' }, { value: 'STAGING', label: 'Staging' }, { value: 'DEVELOPMENT', label: 'Development' }];
function formatDate(value: string) { return new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)); }
const COLUMNS: TableColumn<InstallationSummary>[] = [{ key: 'name', label: 'Installation', render: (installation) => <div className="installation-identity"><strong>{installation.name}</strong><code>{installation.code}</code></div> }, { key: 'clientName', label: 'Client' }, { key: 'productName', label: 'Product' }, { key: 'environment', label: 'Environment' }, { key: 'deploymentMode', label: 'Deployment' }, { key: 'infrastructureOwnership', label: 'Infrastructure' }, { key: 'status', label: 'Status', render: (installation) => <InstallationStatusBadge status={installation.status} /> }, { key: 'updatedAt', label: 'Updated', render: (installation) => formatDate(installation.updatedAt) }];
export function InstallationListPage() {
  const [query, setQuery] = useState<InstallationListQuery>({ search: '', status: 'ALL', environment: 'ALL', page: 1, limit: LIMIT }); const [isCreateOpen, setIsCreateOpen] = useState(false); const [detailId, setDetailId] = useState<string | null>(null); const [editInstallation, setEditInstallation] = useState<InstallationSummary | null>(null); const installationsQuery = useInstallationList(query);
  function updateQuery(nextQuery: Partial<InstallationListQuery>) { setQuery((current) => ({ ...current, ...nextQuery, page: nextQuery.page ?? (nextQuery.search !== undefined || nextQuery.status !== undefined || nextQuery.environment !== undefined ? 1 : current.page) })); }
  if (installationsQuery.isPending) return <div className="installations-page-state"><DLoadingIndicator label="Loading installations" /></div>;
  if (installationsQuery.isError) return <div className="installations-page-state"><DConnectionError title="Installation list unavailable" message="Installation records could not be loaded from the selected data source." detail={installationsQuery.error.message} onRetry={() => void installationsQuery.refetch()} /></div>;
  const result = installationsQuery.data; const actions: TableAction<InstallationSummary>[] = [{ label: 'Open Installation', onClick: (installation) => setDetailId(installation.id) }, { label: 'Edit Installation', onClick: setEditInstallation }];
  return <div className="installations-page"><div className="installations-page-heading"><div><p className="page-eyebrow">Runtime control plane</p><h1>Installations</h1><p>Manage deployed runtime instances for approved client product relationships.</p></div></div><DDataTable columns={COLUMNS} data={result.installations} rowKey="id" searchable searchPlaceholder="Search installation, client, product, or code" searchValue={query.search} onSearchChange={(search) => updateQuery({ search })} filters={<><DStatusFilter label="Status" allLabel="All statuses" options={STATUS_OPTIONS} value={query.status} onChange={(status) => updateQuery({ status: status as InstallationStatus | 'ALL' })} /><DStatusFilter label="Environment" allLabel="All environments" options={ENVIRONMENT_OPTIONS} value={query.environment} onChange={(environment) => updateQuery({ environment: environment as InstallationEnvironment | 'ALL' })} /></>} headerActions={<DButton onClick={() => setIsCreateOpen(true)}>Add Installation</DButton>} pagination={{ page: query.page, pageSize: query.limit, total: result.total }} onPageChange={(page) => updateQuery({ page })} onPageSizeChange={(limit) => updateQuery({ limit, page: 1 })} emptyMessage={<DEmptyState title="No installations found" description="Try another search or filter, or add the first installation." />} onRowClick={(installation) => setDetailId(installation.id)} actions={actions} /><InstallationFormDialog open={isCreateOpen} mode="create" onClose={() => setIsCreateOpen(false)} /><InstallationFormDialog open={editInstallation !== null} mode="edit" installation={editInstallation ?? undefined} onClose={() => setEditInstallation(null)} />{detailId ? <InstallationDetailDialog installationId={detailId} open onClose={() => setDetailId(null)} /> : null}</div>;
}
