import { DButton, DConnectionError, DDataTable, DDialog, DEmptyState, DInput, DSelect, useToast, type TableColumn } from '@digvation-labs/ui';
import { useState } from 'react';
import { useAddRenewalTerm, useClientCommercial, useUpdateProductConfiguration } from '../hooks/use-client-commercial';
import type { BillingCycle, ClientProductCommercialSummary, ProductConfiguration, RenewalTermInput, SubscriptionTerm } from '../types/subscription';
import '../subscriptions.css';

const CYCLE_OPTIONS = [{ value: 'MONTHLY', label: 'Monthly' }, { value: 'QUARTERLY', label: 'Quarterly' }, { value: 'SEMI_ANNUAL', label: 'Semi-annual' }, { value: 'ANNUAL', label: 'Annual' }, { value: 'CUSTOM', label: 'Custom' }];
function money(amountMinor: number, currency: string) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amountMinor / 100); }
function date(value?: string) { return value ? new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(value)) : 'No end date'; }
function expiry(summary: ClientProductCommercialSummary) { const end = summary.currentTerm?.endsAt; if (!end) return 'No fixed expiry'; const days = Math.ceil((new Date(end).getTime() - Date.now()) / 86400000); if (days < 0) return 'Expired'; return days <= (summary.subscription?.renewalNoticeDays ?? 0) ? `Follow up in ${days} days` : `${days} days remaining`; }

function RenewalDialog({ summary, onClose }: { summary: ClientProductCommercialSummary | null; onClose: () => void }) {
  const mutation = useAddRenewalTerm(); const { showToast } = useToast();
  const [values, setValues] = useState<RenewalTermInput>({ startsAt: '', endsAt: '', billingCycle: 'ANNUAL', amountMinor: 0, currency: 'IDR', paymentTermsDays: 30 });
  const subscription = summary?.subscription;
  if (!summary || !subscription) return null;
  const subscriptionId = subscription.id;
  async function submit(event: React.FormEvent) { event.preventDefault(); try { await mutation.mutateAsync({ subscriptionId, input: values }); showToast({ title: 'Renewal term added', variant: 'success' }); onClose(); } catch (error) { showToast({ title: 'Renewal could not be added', description: error instanceof Error ? error.message : 'Check the term dates.', variant: 'danger' }); } }
  return <DDialog open onClose={onClose} title={`Renew ${summary.productName}`} description="A renewal creates a new commercial term and preserves existing history." footer={<div className="client-dialog-actions"><DButton variant="outline" onClick={onClose}>Cancel</DButton><DButton form="renewal-form" type="submit" loading={mutation.isPending}>Add Renewal</DButton></div>}><form id="renewal-form" className="client-contact-form" onSubmit={submit}><div className="client-form-grid"><DInput label="Starts *" placeholder="YYYY-MM-DD" value={values.startsAt} onChange={(startsAt) => setValues((current) => ({ ...current, startsAt }))} /><DInput label="Ends" placeholder="YYYY-MM-DD" value={values.endsAt ?? ''} onChange={(endsAt) => setValues((current) => ({ ...current, endsAt }))} /></div><div className="client-form-grid"><DSelect label="Billing Cycle *" value={values.billingCycle} options={CYCLE_OPTIONS} onValueChange={(billingCycle) => setValues((current) => ({ ...current, billingCycle: billingCycle as BillingCycle }))} /><DInput label="Amount (IDR) *" type="number" value={String(values.amountMinor / 100)} onChange={(amount) => setValues((current) => ({ ...current, amountMinor: Math.max(0, Number(amount || 0) * 100) }))} /></div><DInput label="Payment Terms (days)" type="number" value={String(values.paymentTermsDays ?? '')} onChange={(paymentTermsDays) => setValues((current) => ({ ...current, paymentTermsDays: paymentTermsDays ? Number(paymentTermsDays) : undefined }))} /></form></DDialog>;
}

function ConfigurationDialog({ summary, onClose }: { summary: ClientProductCommercialSummary; onClose: () => void }) {
  const mutation = useUpdateProductConfiguration(); const { showToast } = useToast(); const [configurations, setConfigurations] = useState<ProductConfiguration[]>(summary.configurations);
  async function save() { try { await mutation.mutateAsync({ clientProductId: summary.clientProductId, configurations }); showToast({ title: 'Product configuration updated', variant: 'success' }); onClose(); } catch (error) { showToast({ title: 'Configuration update failed', description: error instanceof Error ? error.message : undefined, variant: 'danger' }); } }
  return <DDialog open onClose={onClose} title={`${summary.productName} configuration`} description="Product-specific limits remain assigned to this client product." footer={<div className="client-dialog-actions"><DButton variant="outline" onClick={onClose}>Cancel</DButton><DButton onClick={() => void save()} loading={mutation.isPending}>Save Changes</DButton></div>}><div className="client-contact-form">{configurations.map((configuration, index) => configuration.valueType === 'BOOLEAN' ? <DSelect key={configuration.id} label={configuration.label} value={String(configuration.value)} options={[{ value: 'true', label: 'Enabled' }, { value: 'false', label: 'Disabled' }]} onValueChange={(value) => setConfigurations((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, value: value === 'true' } : item))} /> : <DInput key={configuration.id} label={configuration.label} type={configuration.valueType === 'INTEGER' ? 'number' : 'text'} value={String(configuration.value)} hint={configuration.unit} onChange={(value) => setConfigurations((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, value: item.valueType === 'INTEGER' ? Number(value || 0) : value } : item))} />)}</div></DDialog>;
}

const TERM_COLUMNS: TableColumn<SubscriptionTerm>[] = [{ key: 'startsAt', label: 'Term', render: (term) => `${date(term.startsAt)} → ${date(term.endsAt)}` }, { key: 'billingCycle', label: 'Billing cycle' }, { key: 'amountMinor', label: 'Amount', render: (term) => money(term.amountMinor, term.currency) }, { key: 'renewedFromTermId', label: 'Type', render: (term) => term.renewedFromTermId ? 'Renewal' : 'Initial' }];

export function ClientCommercialTab({ clientId }: { clientId: string }) {
  const query = useClientCommercial(clientId); const [renewing, setRenewing] = useState<ClientProductCommercialSummary | null>(null); const [configuring, setConfiguring] = useState<ClientProductCommercialSummary | null>(null);
  if (query.isPending) return null;
  if (query.isError) return <DConnectionError title="Commercial records unavailable" message="Subscription records could not be loaded." detail={query.error.message} onRetry={() => void query.refetch()} />;
  if (!query.data.length) return <DEmptyState title="No commercial products" description="Commercial records will appear after a product is assigned." />;
  return <><div className="client-commercial-list">{query.data.map((summary) => <section className="client-commercial-item" key={summary.clientProductId}><div className="client-commercial-header"><div><h2>{summary.productName}</h2><code>{summary.productCode}</code></div><span className={`client-commercial-status is-${(summary.subscription?.status ?? 'PENDING').toLowerCase()}`}>{summary.subscription?.status ?? 'NO SUBSCRIPTION'}</span></div>{summary.currentTerm ? <div className="client-commercial-current"><strong>Current term</strong><span>{date(summary.currentTerm.startsAt)} → {date(summary.currentTerm.endsAt)}</span><span>{money(summary.currentTerm.amountMinor, summary.currentTerm.currency)} / {summary.currentTerm.billingCycle.toLowerCase().replace('_', ' ')}</span><span>{expiry(summary)}</span><span>Auto renew: {summary.subscription?.autoRenew ? 'Yes' : 'No'} · Notice: {summary.subscription?.renewalNoticeDays ?? 0} days</span></div> : <p>No subscription term recorded.</p>}<div className="client-commercial-actions"><DButton variant="outline" onClick={() => setConfiguring(summary)}>Edit Limits</DButton>{summary.subscription ? <DButton variant="outline" onClick={() => setRenewing(summary)}>Add Renewal</DButton> : null}</div><div className="client-configuration-summary">{summary.configurations.length ? summary.configurations.map((configuration) => <span key={configuration.id}>{configuration.label}: <strong>{String(configuration.value)}{configuration.unit ? ` ${configuration.unit}` : ''}</strong></span>) : 'No product-specific limits configured.'}</div><DDataTable columns={TERM_COLUMNS} data={[...summary.terms].sort((left, right) => right.startsAt.localeCompare(left.startsAt))} rowKey="id" /></section>)}</div><RenewalDialog summary={renewing} onClose={() => setRenewing(null)} />{configuring ? <ConfigurationDialog key={configuring.clientProductId} summary={configuring} onClose={() => setConfiguring(null)} /> : null}</>;
}
