import { DInput, DSelect, DTextarea, DToggle } from '@digvation/ui';
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { infrastructureFormSchema, normalizeInfrastructureCode, type InfrastructureFormValues } from '../schemas/infrastructure-form-schema';
const OWNERSHIP_OPTIONS = [{ value: 'DIGVATION', label: 'Digvation' }, { value: 'CLIENT', label: 'Client' }];
const STATUS_OPTIONS = [{ value: 'REGISTERED', label: 'Registered' }, { value: 'ACTIVE', label: 'Active' }, { value: 'MAINTENANCE', label: 'Maintenance' }, { value: 'RETIRED', label: 'Retired' }];
export function InfrastructureForm({ formId, mode, defaultValues, onSubmit }: { formId: string; mode: 'create' | 'edit'; defaultValues: InfrastructureFormValues; onSubmit: (values: InfrastructureFormValues) => void | Promise<void> }) {
  const form = useForm<InfrastructureFormValues>({ defaultValues }); useEffect(() => { form.reset(defaultValues); }, [defaultValues, form]);
  async function submit(values: InfrastructureFormValues) { const result = infrastructureFormSchema.safeParse({ ...values, code: normalizeInfrastructureCode(values.code), region: values.region?.trim() || undefined, hostname: values.hostname?.trim() || undefined, publicAddress: values.publicAddress?.trim() || undefined, privateAddress: values.privateAddress?.trim() || undefined, operatingSystem: values.operatingSystem?.trim() || undefined, architecture: values.architecture?.trim() || undefined, notes: values.notes?.trim() || undefined }); if (!result.success) { result.error.issues.forEach((issue) => form.setError(issue.path[0] as keyof InfrastructureFormValues, { message: issue.message })); return; } await onSubmit(result.data); }
  const capacity = (field: 'cpuCores' | 'memoryMiB' | 'diskGiB', label: string) => <DInput label={label} type="number" min="1" value={form.watch(field)?.toString() ?? ''} error={form.formState.errors[field]?.message} onChange={(value) => form.setValue(field, value ? Number(value) : undefined, { shouldValidate: true })} />;
  return <form className="infrastructure-form" id={formId} onSubmit={form.handleSubmit(submit)} noValidate>
    <section className="infrastructure-form-section"><div className="infrastructure-form-section-heading"><h2>Identity</h2><p>Set the stable registry identity and hosting provider.</p></div><div className="infrastructure-form-grid"><DInput label="Infrastructure Code *" value={form.watch('code')} disabled={mode === 'edit'} hint={mode === 'edit' ? 'Infrastructure code is immutable after creation.' : 'Uppercase letters, numbers, and hyphens only.'} error={form.formState.errors.code?.message} onChange={(value) => form.setValue('code', normalizeInfrastructureCode(value), { shouldValidate: true })} /><DInput label="Name *" value={form.watch('name')} error={form.formState.errors.name?.message} onChange={(value) => form.setValue('name', value, { shouldValidate: true })} /><DInput label="Provider *" value={form.watch('provider')} error={form.formState.errors.provider?.message} onChange={(value) => form.setValue('provider', value, { shouldValidate: true })} /><DInput label="Region" value={form.watch('region') ?? ''} onChange={(value) => form.setValue('region', value, { shouldValidate: true })} /></div></section>
    <section className="infrastructure-form-section"><div className="infrastructure-form-section-heading"><h2>Ownership &amp; lifecycle</h2><p>Lifecycle is the registry state, not live operational health.</p></div><div className="infrastructure-form-grid"><DSelect label="Ownership *" value={form.watch('ownership')} options={OWNERSHIP_OPTIONS} onValueChange={(value) => form.setValue('ownership', value as InfrastructureFormValues['ownership'])} /><DSelect label="Lifecycle status *" value={form.watch('lifecycleStatus')} options={STATUS_OPTIONS} onValueChange={(value) => form.setValue('lifecycleStatus', value as InfrastructureFormValues['lifecycleStatus'])} /></div><div className="infrastructure-managed-toggle"><DToggle label="Managed by Digvation" checked={form.watch('managedByDigvation')} onChange={(value) => form.setValue('managedByDigvation', value)} /></div></section>
    <section className="infrastructure-form-section"><div className="infrastructure-form-section-heading"><h2>Network &amp; platform</h2><p>Only non-secret identifiers and addresses are recorded here.</p></div><div className="infrastructure-form-grid"><DInput label="Hostname" value={form.watch('hostname') ?? ''} onChange={(value) => form.setValue('hostname', value)} /><DInput label="Public address" value={form.watch('publicAddress') ?? ''} onChange={(value) => form.setValue('publicAddress', value)} /><DInput label="Private address" value={form.watch('privateAddress') ?? ''} onChange={(value) => form.setValue('privateAddress', value)} /><DInput label="Operating system" value={form.watch('operatingSystem') ?? ''} onChange={(value) => form.setValue('operatingSystem', value)} /><DInput label="Architecture" value={form.watch('architecture') ?? ''} onChange={(value) => form.setValue('architecture', value)} /></div></section>
    <section className="infrastructure-form-section"><div className="infrastructure-form-section-heading"><h2>Static capacity</h2><p>Registered provisioned capacity only; no live utilization is tracked.</p></div><div className="infrastructure-form-grid">{capacity('cpuCores', 'CPU cores')}{capacity('memoryMiB', 'Total memory (MiB)')}{capacity('diskGiB', 'Total disk (GiB)')}</div></section>
    <section className="infrastructure-form-section"><div className="infrastructure-form-section-heading"><h2>Notes</h2><p>Operational context without credentials or secrets.</p></div><DTextarea label="Notes" value={form.watch('notes') ?? ''} onChange={(value) => form.setValue('notes', value)} /></section>
  </form>;
}
