import { DButton, DDialog, useToast } from '@digvation-labs/ui';
import { useCreateInstallation, useUpdateInstallation } from '../hooks/use-installation-mutations';
import type { InstallationFormValues } from '../schemas/installation-form-schema';
import type { InstallationSummary } from '../types/installation';
import { InstallationForm } from './installation-form';
const FORM_ID = 'installation-form';
export function InstallationFormDialog({ open, mode, installation, onClose }: { open: boolean; mode: 'create' | 'edit'; installation?: InstallationSummary; onClose: () => void }) {
  const createInstallation = useCreateInstallation(); const updateInstallation = useUpdateInstallation(installation?.id ?? ''); const { showToast } = useToast(); const isEditing = mode === 'edit'; const isSubmitting = createInstallation.isPending || updateInstallation.isPending;
  async function submit(values: InstallationFormValues) { try { if (isEditing) { await updateInstallation.mutateAsync({ name: values.name, environment: values.environment, deploymentMode: values.deploymentMode, infrastructureOwnership: values.infrastructureOwnership, managedByDigvation: values.managedByDigvation, region: values.region, applicationUrl: values.applicationUrl }); showToast({ title: 'Installation updated', description: `${values.name} was updated.`, variant: 'success' }); } else { await createInstallation.mutateAsync(values); showToast({ title: 'Installation created', description: `${values.name} starts in provisioning.`, variant: 'success' }); } onClose(); } catch (error) { showToast({ title: isEditing ? 'Installation update failed' : 'Installation creation failed', description: error instanceof Error ? error.message : 'The installation could not be saved.', variant: 'danger' }); } }
  const values: InstallationFormValues = installation ? { clientProductId: installation.clientProductId, code: installation.code, name: installation.name, environment: installation.environment, deploymentMode: installation.deploymentMode, infrastructureOwnership: installation.infrastructureOwnership, managedByDigvation: installation.managedByDigvation, region: installation.region ?? '', applicationUrl: installation.applicationUrl ?? '' } : { clientProductId: '', code: '', name: '', environment: 'PRODUCTION', deploymentMode: 'SHARED', infrastructureOwnership: 'DIGVATION', managedByDigvation: true, region: '', applicationUrl: '' };
  return <DDialog open={open} onClose={() => !isSubmitting && onClose()} title={isEditing ? `Edit ${installation?.name ?? 'installation'}` : 'Add installation'} description={isEditing ? 'Update installation configuration. Its code and client product remain stable.' : 'Create a runtime instance for an existing client product.'} footer={<div className="installation-dialog-actions"><DButton variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</DButton><DButton form={FORM_ID} type="submit" loading={isSubmitting}>{isEditing ? 'Save Changes' : 'Create Installation'}</DButton></div>}><InstallationForm formId={FORM_ID} mode={mode} defaultValues={values} onSubmit={submit} /></DDialog>;
}
