import { DButton, DDialog, DEmptyState, DLoadingIndicator, useToast } from '@digvation-labs/ui';
import { useCreateInstallation, useUpdateInstallation } from '../hooks/use-installation-mutations';
import { useClientProductOptions } from '../hooks/use-installations';
import type { InstallationFormValues } from '../schemas/installation-form-schema';
import type { InstallationSummary } from '../types/installation';
import { InstallationForm } from './installation-form';
const FORM_ID = 'installation-form';
export function InstallationFormDialog({ open, mode, installation, initialClientProduct, onClose }: { open: boolean; mode: 'create' | 'edit'; installation?: InstallationSummary; initialClientProduct?: { id: string; label: string }; onClose: () => void }) {
  const createInstallation = useCreateInstallation(); const updateInstallation = useUpdateInstallation(installation?.id ?? ''); const { showToast } = useToast(); const isEditing = mode === 'edit'; const isSubmitting = createInstallation.isPending || updateInstallation.isPending;
  const clientProductOptionsQuery = useClientProductOptions();
  async function submit(values: InstallationFormValues) { try { if (isEditing) { await updateInstallation.mutateAsync({ name: values.name, environment: values.environment, deploymentMode: values.deploymentMode, infrastructureOwnership: values.infrastructureOwnership, managedByDigvation: values.managedByDigvation, region: values.region, applicationUrl: values.applicationUrl }); showToast({ title: 'Installation updated', description: `${values.name} was updated.`, variant: 'success' }); } else { await createInstallation.mutateAsync(values); showToast({ title: 'Installation created', description: `${values.name} starts in provisioning.`, variant: 'success' }); } onClose(); } catch (error) { showToast({ title: isEditing ? 'Installation update failed' : 'Installation creation failed', description: error instanceof Error ? error.message : 'The installation could not be saved.', variant: 'danger' }); } }
  const values: InstallationFormValues = installation ? { clientProductId: installation.clientProductId, code: installation.code, name: installation.name, environment: installation.environment, deploymentMode: installation.deploymentMode, infrastructureOwnership: installation.infrastructureOwnership, managedByDigvation: installation.managedByDigvation, region: installation.region ?? '', applicationUrl: installation.applicationUrl ?? '' } : { clientProductId: initialClientProduct?.id ?? '', code: '', name: '', environment: 'PRODUCTION', deploymentMode: 'SHARED', infrastructureOwnership: 'DIGVATION', managedByDigvation: true, region: '', applicationUrl: '' };
  const hasNoEligibleClientProducts = !isEditing && !initialClientProduct && clientProductOptionsQuery.isSuccess && clientProductOptionsQuery.data.length === 0;
  const content = hasNoEligibleClientProducts ? <DEmptyState title="No client products available" description="Assign a product to a client first, then create its installation from that client product relationship." /> : clientProductOptionsQuery.isPending && !isEditing ? <div className="installation-form-state"><DLoadingIndicator label="Loading client product relationships" /></div> : <InstallationForm formId={FORM_ID} mode={mode} defaultValues={values} lockedClientProductLabel={initialClientProduct?.label} onSubmit={submit} />;
  return <DDialog open={open} onClose={() => !isSubmitting && onClose()} title={isEditing ? `Edit ${installation?.name ?? 'installation'}` : 'Add installation'} description={isEditing ? 'Update installation configuration. Its code and client product remain stable.' : initialClientProduct ? `Create a runtime instance for ${initialClientProduct.label}.` : 'Create a runtime instance for an existing client product.'} footer={<div className="installation-dialog-actions"><DButton variant="outline" onClick={onClose} disabled={isSubmitting}>{hasNoEligibleClientProducts ? 'Close' : 'Cancel'}</DButton>{hasNoEligibleClientProducts ? null : <DButton form={FORM_ID} type="submit" loading={isSubmitting}>{isEditing ? 'Save Changes' : 'Create Installation'}</DButton>}</div>}>{content}</DDialog>;
}
